INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1101, 11, 'KAB. ACEH SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1102, 11, 'KAB. ACEH TENGGARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1103, 11, 'KAB. ACEH TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1104, 11, 'KAB. ACEH TENGAH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1105, 11, 'KAB. ACEH BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1106, 11, 'KAB. ACEH BESAR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1107, 11, 'KAB. PIDIE', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1108, 11, 'KAB. ACEH UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1109, 11, 'KAB. SIMEULUE', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1110, 11, 'KAB. ACEH SINGKIL', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1111, 11, 'KAB. BIREUEN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1112, 11, 'KAB. ACEH BARAT DAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1113, 11, 'KAB. GAYO LUES', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1114, 11, 'KAB. ACEH JAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1115, 11, 'KAB. NAGAN RAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1116, 11, 'KAB. ACEH TAMIANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1117, 11, 'KAB. BENER MERIAH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1118, 11, 'KAB. PIDIE JAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1171, 11, 'KOTA BANDA ACEH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1172, 11, 'KOTA SABANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1173, 11, 'KOTA LHOKSEUMAWE', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1174, 11, 'KOTA LANGSA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1175, 11, 'KOTA SUBULUSSALAM', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1201, 12, 'KAB. TAPANULI TENGAH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1202, 12, 'KAB. TAPANULI UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1203, 12, 'KAB. TAPANULI SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1204, 12, 'KAB. NIAS', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1205, 12, 'KAB. LANGKAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1206, 12, 'KAB. KARO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1207, 12, 'KAB. DELI SERDANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1208, 12, 'KAB. SIMALUNGUN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1209, 12, 'KAB. ASAHAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1210, 12, 'KAB. LABUHANBATU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1211, 12, 'KAB. DAIRI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1212, 12, 'KAB. TOBA SAMOSIR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1213, 12, 'KAB. MANDAILING NATAL', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1214, 12, 'KAB. NIAS SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1215, 12, 'KAB. PAKPAK BHARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1216, 12, 'KAB. HUMBANG HASUNDUTAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1217, 12, 'KAB. SAMOSIR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1218, 12, 'KAB. SERDANG BEDAGAI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1219, 12, 'KAB. BATU BARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1220, 12, 'KAB. PADANG LAWAS UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1221, 12, 'KAB. PADANG LAWAS', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1222, 12, 'KAB. LABUHANBATU SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1223, 12, 'KAB. LABUHANBATU UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1224, 12, 'KAB. NIAS UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1225, 12, 'KAB. NIAS BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1271, 12, 'KOTA MEDAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1272, 12, 'KOTA PEMATANG SIANTAR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1273, 12, 'KOTA SIBOLGA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1274, 12, 'KOTA TANJUNG BALAI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1275, 12, 'KOTA BINJAI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1276, 12, 'KOTA TEBING TINGGI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1277, 12, 'KOTA PADANGSIDIMPUAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1278, 12, 'KOTA GUNUNGSITOLI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1301, 13, 'KAB. PESISIR SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1302, 13, 'KAB. SOLOK', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1303, 13, 'KAB. SIJUNJUNG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1304, 13, 'KAB. TANAH DATAR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1305, 13, 'KAB. PADANG PARIAMAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1306, 13, 'KAB. AGAM', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1307, 13, 'KAB. LIMA PULUH KOTA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1308, 13, 'KAB. PASAMAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1309, 13, 'KAB. KEPULAUAN MENTAWAI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1310, 13, 'KAB. DHARMASRAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1311, 13, 'KAB. SOLOK SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1312, 13, 'KAB. PASAMAN BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1371, 13, 'KOTA PADANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1372, 13, 'KOTA SOLOK', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1373, 13, 'KOTA SAWAHLUNTO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1374, 13, 'KOTA PADANG PANJANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1375, 13, 'KOTA BUKITTINGGI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1376, 13, 'KOTA PAYAKUMBUH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1377, 13, 'KOTA PARIAMAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1401, 14, 'KAB. KAMPAR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1402, 14, 'KAB. INDRAGIRI HULU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1403, 14, 'KAB. BENGKALIS', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1404, 14, 'KAB. INDRAGIRI HILIR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1405, 14, 'KAB. PELALAWAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1406, 14, 'KAB. ROKAN HULU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1407, 14, 'KAB. ROKAN HILIR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1408, 14, 'KAB. SIAK', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1409, 14, 'KAB. KUANTAN SINGINGI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1410, 14, 'KAB. KEPULAUAN MERANTI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1471, 14, 'KOTA PEKANBARU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1472, 14, 'KOTA DUMAI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1501, 15, 'KAB. KERINCI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1502, 15, 'KAB. MERANGIN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1503, 15, 'KAB. SAROLANGUN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1504, 15, 'KAB. BATANGHARI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1505, 15, 'KAB. MUARO JAMBI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1506, 15, 'KAB. TANJUNG JABUNG BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1507, 15, 'KAB. TANJUNG JABUNG TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1508, 15, 'KAB. BUNGO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1509, 15, 'KAB. TEBO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1571, 15, 'KOTA JAMBI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1572, 15, 'KOTA SUNGAI PENUH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1601, 16, 'KAB. OGAN KOMERING ULU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1602, 16, 'KAB. OGAN KOMERING ILIR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1603, 16, 'KAB. MUARA ENIM', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1604, 16, 'KAB. LAHAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1605, 16, 'KAB. MUSI RAWAS', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1606, 16, 'KAB. MUSI BANYUASIN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1607, 16, 'KAB. BANYUASIN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1608, 16, 'KAB. OGAN KOMERING ULU TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1609, 16, 'KAB. OGAN KOMERING ULU SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1610, 16, 'KAB. OGAN ILIR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1611, 16, 'KAB. EMPAT LAWANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1612, 16, 'KAB. PENUKAL ABAB LEMATANG ILIR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1613, 16, 'KAB. MUSI RAWAS UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1671, 16, 'KOTA PALEMBANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1672, 16, 'KOTA PAGAR ALAM', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1673, 16, 'KOTA LUBUK LINGGAU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1674, 16, 'KOTA PRABUMULIH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1701, 17, 'KAB. BENGKULU SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1702, 17, 'KAB. REJANG LEBONG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1703, 17, 'KAB. BENGKULU UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1704, 17, 'KAB. KAUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1705, 17, 'KAB. SELUMA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1706, 17, 'KAB. MUKO MUKO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1707, 17, 'KAB. LEBONG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1708, 17, 'KAB. KEPAHIANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1709, 17, 'KAB. BENGKULU TENGAH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1771, 17, 'KOTA BENGKULU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1801, 18, 'KAB. LAMPUNG SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1802, 18, 'KAB. LAMPUNG TENGAH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1803, 18, 'KAB. LAMPUNG UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1804, 18, 'KAB. LAMPUNG BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1805, 18, 'KAB. TULANG BAWANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1806, 18, 'KAB. TANGGAMUS', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1807, 18, 'KAB. LAMPUNG TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1808, 18, 'KAB. WAY KANAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1809, 18, 'KAB. PESAWARAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1810, 18, 'KAB. PRINGSEWU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1811, 18, 'KAB. MESUJI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1812, 18, 'KAB. TULANG BAWANG BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1813, 18, 'KAB. PESISIR BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1871, 18, 'KOTA BANDAR LAMPUNG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1872, 18, 'KOTA METRO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1901, 19, 'KAB. BANGKA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1902, 19, 'KAB. BELITUNG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1903, 19, 'KAB. BANGKA SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1904, 19, 'KAB. BANGKA TENGAH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1905, 19, 'KAB. BANGKA BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1906, 19, 'KAB. BELITUNG TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (1971, 19, 'KOTA PANGKAL PINANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (2101, 21, 'KAB. BINTAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (2102, 21, 'KAB. KARIMUN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (2103, 21, 'KAB. NATUNA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (2104, 21, 'KAB. LINGGA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (2105, 21, 'KAB. KEPULAUAN ANAMBAS', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (2171, 21, 'KOTA BATAM', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (2172, 21, 'KOTA TANJUNG PINANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3101, 31, 'KAB. ADM. KEP. SERIBU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3171, 31, 'KOTA ADM. JAKARTA PUSAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3172, 31, 'KOTA ADM. JAKARTA UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3173, 31, 'KOTA ADM. JAKARTA BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3174, 31, 'KOTA ADM. JAKARTA SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3175, 31, 'KOTA ADM. JAKARTA TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3201, 32, 'KAB. BOGOR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3202, 32, 'KAB. SUKABUMI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3203, 32, 'KAB. CIANJUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3204, 32, 'KAB. BANDUNG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3205, 32, 'KAB. GARUT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3206, 32, 'KAB. TASIKMALAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3207, 32, 'KAB. CIAMIS', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3208, 32, 'KAB. KUNINGAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3209, 32, 'KAB. CIREBON', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3210, 32, 'KAB. MAJALENGKA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3211, 32, 'KAB. SUMEDANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3212, 32, 'KAB. INDRAMAYU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3213, 32, 'KAB. SUBANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3214, 32, 'KAB. PURWAKARTA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3215, 32, 'KAB. KARAWANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3216, 32, 'KAB. BEKASI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3217, 32, 'KAB. BANDUNG BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3218, 32, 'KAB. PANGANDARAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3271, 32, 'KOTA BOGOR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3272, 32, 'KOTA SUKABUMI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3273, 32, 'KOTA BANDUNG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3274, 32, 'KOTA CIREBON', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3275, 32, 'KOTA BEKASI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3276, 32, 'KOTA DEPOK', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3277, 32, 'KOTA CIMAHI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3278, 32, 'KOTA TASIKMALAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3279, 32, 'KOTA BANJAR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3301, 33, 'KAB. CILACAP', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3302, 33, 'KAB. BANYUMAS', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3303, 33, 'KAB. PURBALINGGA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3304, 33, 'KAB. BANJARNEGARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3305, 33, 'KAB. KEBUMEN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3306, 33, 'KAB. PURWOREJO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3307, 33, 'KAB. WONOSOBO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3308, 33, 'KAB. MAGELANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3309, 33, 'KAB. BOYOLALI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3310, 33, 'KAB. KLATEN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3311, 33, 'KAB. SUKOHARJO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3312, 33, 'KAB. WONOGIRI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3313, 33, 'KAB. KARANGANYAR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3314, 33, 'KAB. SRAGEN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3315, 33, 'KAB. GROBOGAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3316, 33, 'KAB. BLORA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3317, 33, 'KAB. REMBANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3318, 33, 'KAB. PATI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3319, 33, 'KAB. KUDUS', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3320, 33, 'KAB. JEPARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3321, 33, 'KAB. DEMAK', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3322, 33, 'KAB. SEMARANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3323, 33, 'KAB. TEMANGGUNG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3324, 33, 'KAB. KENDAL', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3325, 33, 'KAB. BATANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3326, 33, 'KAB. PEKALONGAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3327, 33, 'KAB. PEMALANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3328, 33, 'KAB. TEGAL', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3329, 33, 'KAB. BREBES', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3371, 33, 'KOTA MAGELANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3372, 33, 'KOTA SURAKARTA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3373, 33, 'KOTA SALATIGA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3374, 33, 'KOTA SEMARANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3375, 33, 'KOTA PEKALONGAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3376, 33, 'KOTA TEGAL', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3401, 34, 'KAB. KULON PROGO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3402, 34, 'KAB. BANTUL', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3403, 34, 'KAB. GUNUNG KIDUL', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3404, 34, 'KAB. SLEMAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3471, 34, 'KOTA YOGYAKARTA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3501, 35, 'KAB. PACITAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3502, 35, 'KAB. PONOROGO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3503, 35, 'KAB. TRENGGALEK', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3504, 35, 'KAB. TULUNGAGUNG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3505, 35, 'KAB. BLITAR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3506, 35, 'KAB. KEDIRI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3507, 35, 'KAB. MALANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3508, 35, 'KAB. LUMAJANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3509, 35, 'KAB. JEMBER', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3510, 35, 'KAB. BANYUWANGI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3511, 35, 'KAB. BONDOWOSO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3512, 35, 'KAB. SITUBONDO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3513, 35, 'KAB. PROBOLINGGO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3514, 35, 'KAB. PASURUAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3515, 35, 'KAB. SIDOARJO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3516, 35, 'KAB. MOJOKERTO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3517, 35, 'KAB. JOMBANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3518, 35, 'KAB. NGANJUK', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3519, 35, 'KAB. MADIUN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3520, 35, 'KAB. MAGETAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3521, 35, 'KAB. NGAWI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3522, 35, 'KAB. BOJONEGORO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3523, 35, 'KAB. TUBAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3524, 35, 'KAB. LAMONGAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3525, 35, 'KAB. GRESIK', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3526, 35, 'KAB. BANGKALAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3527, 35, 'KAB. SAMPANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3528, 35, 'KAB. PAMEKASAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3529, 35, 'KAB. SUMENEP', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3571, 35, 'KOTA KEDIRI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3572, 35, 'KOTA BLITAR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3573, 35, 'KOTA MALANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3574, 35, 'KOTA PROBOLINGGO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3575, 35, 'KOTA PASURUAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3576, 35, 'KOTA MOJOKERTO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3577, 35, 'KOTA MADIUN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3578, 35, 'KOTA SURABAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3579, 35, 'KOTA BATU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3601, 36, 'KAB. PANDEGLANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3602, 36, 'KAB. LEBAK', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3603, 36, 'KAB. TANGERANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3604, 36, 'KAB. SERANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3671, 36, 'KOTA TANGERANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3672, 36, 'KOTA CILEGON', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3673, 36, 'KOTA SERANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (3674, 36, 'KOTA TANGERANG SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5101, 51, 'KAB. JEMBRANA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5102, 51, 'KAB. TABANAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5103, 51, 'KAB. BADUNG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5104, 51, 'KAB. GIANYAR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5105, 51, 'KAB. KLUNGKUNG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5106, 51, 'KAB. BANGLI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5107, 51, 'KAB. KARANGASEM', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5108, 51, 'KAB. BULELENG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5171, 51, 'KOTA DENPASAR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5201, 52, 'KAB. LOMBOK BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5202, 52, 'KAB. LOMBOK TENGAH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5203, 52, 'KAB. LOMBOK TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5204, 52, 'KAB. SUMBAWA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5205, 52, 'KAB. DOMPU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5206, 52, 'KAB. BIMA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5207, 52, 'KAB. SUMBAWA BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5208, 52, 'KAB. LOMBOK UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5271, 52, 'KOTA MATARAM', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5272, 52, 'KOTA BIMA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5301, 53, 'KAB. KUPANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5302, 53, 'KAB TIMOR TENGAH SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5303, 53, 'KAB. TIMOR TENGAH UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5304, 53, 'KAB. BELU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5305, 53, 'KAB. ALOR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5306, 53, 'KAB. FLORES TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5307, 53, 'KAB. SIKKA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5308, 53, 'KAB. ENDE', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5309, 53, 'KAB. NGADA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5310, 53, 'KAB. MANGGARAI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5311, 53, 'KAB. SUMBA TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5312, 53, 'KAB. SUMBA BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5313, 53, 'KAB. LEMBATA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5314, 53, 'KAB. ROTE NDAO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5315, 53, 'KAB. MANGGARAI BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5316, 53, 'KAB. NAGEKEO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5317, 53, 'KAB. SUMBA TENGAH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5318, 53, 'KAB. SUMBA BARAT DAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5319, 53, 'KAB. MANGGARAI TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5320, 53, 'KAB. SABU RAIJUA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5321, 53, 'KAB. MALAKA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (5371, 53, 'KOTA KUPANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6101, 61, 'KAB. SAMBAS', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6102, 61, 'KAB. MEMPAWAH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6103, 61, 'KAB. SANGGAU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6104, 61, 'KAB. KETAPANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6105, 61, 'KAB. SINTANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6106, 61, 'KAB. KAPUAS HULU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6107, 61, 'KAB. BENGKAYANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6108, 61, 'KAB. LANDAK', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6109, 61, 'KAB. SEKADAU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6110, 61, 'KAB. MELAWI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6111, 61, 'KAB. KAYONG UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6112, 61, 'KAB. KUBU RAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6171, 61, 'KOTA PONTIANAK', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6172, 61, 'KOTA SINGKAWANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6201, 62, 'KAB. KOTAWARINGIN BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6202, 62, 'KAB. KOTAWARINGIN TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6203, 62, 'KAB. KAPUAS', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6204, 62, 'KAB. BARITO SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6205, 62, 'KAB. BARITO UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6206, 62, 'KAB. KATINGAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6207, 62, 'KAB. SERUYAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6208, 62, 'KAB. SUKAMARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6209, 62, 'KAB. LAMANDAU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6210, 62, 'KAB. GUNUNG MAS', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6211, 62, 'KAB. PULANG PISAU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6212, 62, 'KAB. MURUNG RAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6213, 62, 'KAB. BARITO TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6271, 62, 'KOTA PALANGKARAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6301, 63, 'KAB. TANAH LAUT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6302, 63, 'KAB. KOTABARU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6303, 63, 'KAB. BANJAR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6304, 63, 'KAB. BARITO KUALA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6305, 63, 'KAB. TAPIN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6306, 63, 'KAB. HULU SUNGAI SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6307, 63, 'KAB. HULU SUNGAI TENGAH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6308, 63, 'KAB. HULU SUNGAI UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6309, 63, 'KAB. TABALONG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6310, 63, 'KAB. TANAH BUMBU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6311, 63, 'KAB. BALANGAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6371, 63, 'KOTA BANJARMASIN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6372, 63, 'KOTA BANJARBARU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6401, 64, 'KAB. PASER', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6402, 64, 'KAB. KUTAI KARTANEGARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6403, 64, 'KAB. BERAU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6407, 64, 'KAB. KUTAI BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6408, 64, 'KAB. KUTAI TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6409, 64, 'KAB. PENAJAM PASER UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6411, 64, 'KAB. MAHAKAM ULU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6471, 64, 'KOTA BALIKPAPAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6472, 64, 'KOTA SAMARINDA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6474, 64, 'KOTA BONTANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6501, 65, 'KAB. BULUNGAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6502, 65, 'KAB. MALINAU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6503, 65, 'KAB. NUNUKAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6504, 65, 'KAB. TANA TIDUNG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (6571, 65, 'KOTA TARAKAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7101, 71, 'KAB. BOLAANG MONGONDOW', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7102, 71, 'KAB. MINAHASA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7103, 71, 'KAB. KEPULAUAN SANGIHE', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7104, 71, 'KAB. KEPULAUAN TALAUD', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7105, 71, 'KAB. MINAHASA SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7106, 71, 'KAB. MINAHASA UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7107, 71, 'KAB. MINAHASA TENGGARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7108, 71, 'KAB. BOLAANG MONGONDOW UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7109, 71, 'KAB. KEP. SIAU TAGULANDANG BIARO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7110, 71, 'KAB. BOLAANG MONGONDOW TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7111, 71, 'KAB. BOLAANG MONGONDOW SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7171, 71, 'KOTA MANADO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7172, 71, 'KOTA BITUNG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7173, 71, 'KOTA TOMOHON', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7174, 71, 'KOTA KOTAMOBAGU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7201, 72, 'KAB. BANGGAI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7202, 72, 'KAB. POSO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7203, 72, 'KAB. DONGGALA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7204, 72, 'KAB. TOLI TOLI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7205, 72, 'KAB. BUOL', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7206, 72, 'KAB. MOROWALI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7207, 72, 'KAB. BANGGAI KEPULAUAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7208, 72, 'KAB. PARIGI MOUTONG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7209, 72, 'KAB. TOJO UNA UNA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7210, 72, 'KAB. SIGI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7211, 72, 'KAB. BANGGAI LAUT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7212, 72, 'KAB. MOROWALI UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7271, 72, 'KOTA PALU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7301, 73, 'KAB. KEPULAUAN SELAYAR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7302, 73, 'KAB. BULUKUMBA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7303, 73, 'KAB. BANTAENG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7304, 73, 'KAB. JENEPONTO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7305, 73, 'KAB. TAKALAR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7306, 73, 'KAB. GOWA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7307, 73, 'KAB. SINJAI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7308, 73, 'KAB. BONE', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7309, 73, 'KAB. MAROS', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7310, 73, 'KAB. PANGKAJENE KEPULAUAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7311, 73, 'KAB. BARRU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7312, 73, 'KAB. SOPPENG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7313, 73, 'KAB. WAJO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7314, 73, 'KAB. SIDENRENG RAPPANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7315, 73, 'KAB. PINRANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7316, 73, 'KAB. ENREKANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7317, 73, 'KAB. LUWU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7318, 73, 'KAB. TANA TORAJA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7322, 73, 'KAB. LUWU UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7324, 73, 'KAB. LUWU TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7326, 73, 'KAB. TORAJA UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7371, 73, 'KOTA MAKASSAR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7372, 73, 'KOTA PARE PARE', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7373, 73, 'KOTA PALOPO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7401, 74, 'KAB. KOLAKA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7402, 74, 'KAB. KONAWE', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7403, 74, 'KAB. MUNA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7404, 74, 'KAB. BUTON', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7405, 74, 'KAB. KONAWE SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7406, 74, 'KAB. BOMBANA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7407, 74, 'KAB. WAKATOBI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7408, 74, 'KAB. KOLAKA UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7409, 74, 'KAB. KONAWE UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7410, 74, 'KAB. BUTON UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7411, 74, 'KAB. KOLAKA TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7412, 74, 'KAB. KONAWE KEPULAUAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7413, 74, 'KAB. MUNA BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7414, 74, 'KAB. BUTON TENGAH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7415, 74, 'KAB. BUTON SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7471, 74, 'KOTA KENDARI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7472, 74, 'KOTA BAU BAU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7501, 75, 'KAB. GORONTALO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7502, 75, 'KAB. BOALEMO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7503, 75, 'KAB. BONE BOLANGO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7504, 75, 'KAB. PAHUWATO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7505, 75, 'KAB. GORONTALO UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7571, 75, 'KOTA GORONTALO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7601, 76, 'KAB. MAMUJU UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7602, 76, 'KAB. MAMUJU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7603, 76, 'KAB. MAMASA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7604, 76, 'KAB. POLEWALI MANDAR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7605, 76, 'KAB. MAJENE', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (7606, 76, 'KAB. MAMUJU TENGAH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8101, 81, 'KAB. MALUKU TENGAH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8102, 81, 'KAB. MALUKU TENGGARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8103, 81, 'KAB MALUKU TENGGARA BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8104, 81, 'KAB. BURU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8105, 81, 'KAB. SERAM BAGIAN TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8106, 81, 'KAB. SERAM BAGIAN BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8107, 81, 'KAB. KEPULAUAN ARU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8108, 81, 'KAB. MALUKU BARAT DAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8109, 81, 'KAB. BURU SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8171, 81, 'KOTA AMBON', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8172, 81, 'KOTA TUAL', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8201, 82, 'KAB. HALMAHERA BARAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8202, 82, 'KAB. HALMAHERA TENGAH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8203, 82, 'KAB. HALMAHERA UTARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8204, 82, 'KAB. HALMAHERA SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8205, 82, 'KAB. KEPULAUAN SULA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8206, 82, 'KAB. HALMAHERA TIMUR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8207, 82, 'KAB. PULAU MOROTAI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8208, 82, 'KAB. PULAU TALIABU', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8271, 82, 'KOTA TERNATE', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (8272, 82, 'KOTA TIDORE KEPULAUAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9101, 91, 'KAB. MERAUKE', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9102, 91, 'KAB. JAYAWIJAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9103, 91, 'KAB. JAYAPURA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9104, 91, 'KAB. NABIRE', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9105, 91, 'KAB. KEPULAUAN YAPEN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9106, 91, 'KAB. BIAK NUMFOR', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9107, 91, 'KAB. PUNCAK JAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9108, 91, 'KAB. PANIAI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9109, 91, 'KAB. MIMIKA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9110, 91, 'KAB. SARMI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9111, 91, 'KAB. KEEROM', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9112, 91, 'KAB PEGUNUNGAN BINTANG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9113, 91, 'KAB. YAHUKIMO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9114, 91, 'KAB. TOLIKARA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9115, 91, 'KAB. WAROPEN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9116, 91, 'KAB. BOVEN DIGOEL', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9117, 91, 'KAB. MAPPI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9118, 91, 'KAB. ASMAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9119, 91, 'KAB. SUPIORI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9120, 91, 'KAB. MAMBERAMO RAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9121, 91, 'KAB. MAMBERAMO TENGAH', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9122, 91, 'KAB. YALIMO', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9123, 91, 'KAB. LANNY JAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9124, 91, 'KAB. NDUGA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9125, 91, 'KAB. PUNCAK', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9126, 91, 'KAB. DOGIYAI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9127, 91, 'KAB. INTAN JAYA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9128, 91, 'KAB. DEIYAI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9171, 91, 'KOTA JAYAPURA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9201, 92, 'KAB. SORONG', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9202, 92, 'KAB. MANOKWARI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9203, 92, 'KAB. FAK FAK', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9204, 92, 'KAB. SORONG SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9205, 92, 'KAB. RAJA AMPAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9206, 92, 'KAB. TELUK BINTUNI', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9207, 92, 'KAB. TELUK WONDAMA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9208, 92, 'KAB. KAIMANA', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9209, 92, 'KAB. TAMBRAUW', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9210, 92, 'KAB. MAYBRAT', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9211, 92, 'KAB. MANOKWARI SELATAN', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9212, 92, 'KAB. PEGUNUNGAN ARFAK', NULL, NULL, NULL);
INSERT INTO `sibea_kabupaten_kota` (`id`, `provinsi_id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (9271, 92, 'KOTA SORONG', NULL, NULL, NULL);
