INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (11, 'Aceh', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (12, 'Sumatera Utara', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (13, 'Sumatera Barat', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (14, 'Riau', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (15, 'Jambi', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (16, 'Sumatera Selatan', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (17, 'Bengkulu', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (18, 'Lampung', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (19, 'Kepulauan Bangka Belitung', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (21, 'Kepulauan Riau', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (31, 'DKI Jakarta', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (32, 'Jawa Barat', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (33, 'Jawa Tengah', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (34, 'DI Yogyakarta', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (35, 'Jawa Timur', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (36, 'Banten', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (51, 'Bali', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (52, 'Nusa Tenggara Barat', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (53, 'Nusa Tenggara Timur', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (61, 'Kalimantan Barat', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (62, 'Kalimantan Tengah', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (63, 'Kalimantan Selatan', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (64, 'Kalimantan Timur', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (65, 'Kalimantan Utara', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (71, 'Sulawesi Utara', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (72, 'Sulawesi Tengah', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (73, 'Sulawesi Selatan', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (74, 'Sulawesi Tenggara', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (75, 'Gorontalo', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (76, 'Sulawesi Barat', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (81, 'Maluku', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (82, 'Maluku Utara', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (91, 'Papua Barat', NULL, NULL, NULL);
INSERT INTO `sibea_provinsi` (`id`, `nama`, `created_at`, `updated_at`, `deleted_at`) VALUES (92, 'Papua', NULL, NULL, NULL);
